Update notification db and deploy.yml
Cambiado region2

diff --git a/github/workflow/deploy.yml b/github/workflow/deploy.yml
--- a/github/workflow/deploy.yml
+++ b/github/workflow/deploy.yml
@@ -4,7 +4,16 @@ on:
   push:
     branches:
       - main
-
+env:
+  AWS_REGION: ${{ secrets.AWS_REGION }}                  # set this to your preferred AWS region, e.g. us-west-1
+  ECR_REGISTRY: 339712766050.dkr.ecr.us-east-2.amazonaws.com  # set this to your ECR registry
+  ECR_REPOSITORY: grupo14-cinema-platform           # set this to your Amazon ECR repository name
+  ECS_SERVICE: srv-cinema-platform-g14                # set this to your Amazon ECS service name
+  ECS_CLUSTER: app-cinema-platform                # set this to your Amazon ECS cluster name
+  ECS_TASK_DEFINITION:  task-cinema-platform-frontend  # set this to the path to your Amazon ECS task definition
+                                               # file, e.g. .aws/task-definition.json
+  CONTAINER_NAME: cinemaFrontend                  # set this to the name of the container in the
+                                               # containerDefinitions section of your task definition
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -12,7 +21,109 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
+      
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v1
 
+    - name: Login to DockerHub
+      uses: docker/login-action@v1
+      with:
+        username: ${{ secrets.DOCKERHUB_USERNAME }}
+        password: ${{ secrets.DOCKERHUB_PASSWORD }}
+
+    - name: Build up Dockers
+      run: |
+        services=(
+          "createCommentary" "createProject" "deleteCommentary" "deleteProject" 
+          "notificationHistory" "readCommentaries" "readProject" "receiveNotification" 
+          "sendNotification" "updateCommentary" "updateProject"
+        )
+        
+        for service in "${services[@]}"
+        do
+          if [ -d "$service" ]; then
+            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest ./$service
+            docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest
+          else
+            echo "Failed to find the path of directory of service $service"
+            exit 1
+          fi
+        done
+
+    - name: Paths of docker-compose
+      run: |
+        sed -i 's|build: \./|build: ../|g' ./docker/docker-compose.yml
+        echo "Content Updated of docker-compose.yml:"
+        cat ./docker/docker-compose.yml
+
+    - name: Clean up previous containers
+      run: |
+        docker-compose -f ./docker/docker-compose.yml down
+
+    - name: Execute Docker Compose
+      run: |
+        docker-compose -f ./docker/docker-compose.yml up -d
+
+  deploy-AWS:
+    needs: [build-and-push]  
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Set permissions for private key
+      run: |
+        echo "${{ secrets.AWS_PRIVATE_KEY }}" > key.pem
+        chmod 600 key.pem
+
+    - name: Pull Docker images
+      run: |
+        services=(
+          "createCommentary" "createProject" "deleteCommentary" "deleteProject" 
+          "notificationHistory" "readCommentaries" "readProject" "receiveNotification" 
+          "sendNotification" "updateCommentary" "updateProject"
+        )
+
+        for service in "${services[@]}"
+        do
+          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_HOST }} "sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest"
+        done
+
+    - name: Stop running containers
+      run: |
+        services=(
+          "createCommentary" "createProject" "deleteCommentary" "deleteProject" 
+          "notificationHistory" "readCommentaries" "readProject" "receiveNotification" 
+          "sendNotification" "updateCommentary" "updateProject"
+        )
+
+        for service in "${services[@]}"
+        do
+          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_HOST }} "sudo docker stop $service-plataform-aws || true"
+          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_HOST }} "sudo docker rm $service-plataform-aws || true"
+        done
+
+    - name: Remove old Docker images
+      run: |
+        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_HOST }} 'sudo docker image prune -f'
+
+    - name: Run new containers
+      run: |
+        services=(
+          "createCommentary" "createProject" "deleteCommentary" "deleteProject" 
+          "notificationHistory" "readCommentaries" "readProject" "receiveNotification" 
+          "sendNotification" "updateCommentary" "updateProject"
+        )
+
+        ports=(3001 3002 3003 3004 3005 3006 3007 3008 3009 3010 3011)
+
+        i=0
+        for service in "${services[@]}"
+        do
+          port=${ports[$i]}
+          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_HOST }} "sudo docker run -d --name $service-plataform-aws -p $((8080 + i)):$port ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest"
+          i=$((i + 1))
+        done
+
+        
     - name: Set up Node.js
       uses: actions/setup-node@v2
       with:
