Validate docker-compose

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -24,50 +24,26 @@ jobs:
 
 
 
-    - name: Build and push each microservice
+    - name: Build up Dockers
       run: |
-          services=(
-            "createcommentary" "createproject" "deletecommentary" "deleteproject" 
-            "notificationhistory" "readcommentaries" "readproject" "receivenotification" 
-            "sendnotification" "updatecommentary" "updateproject" "audit-service" "create-user"
-            "createdocument" "delete-user" "deletedocument" "login" "read-user" "readdocument"
-            "update-user" "updatedocument"
-          )
-          
-          for service in "${services[@]}"
-          do
-            if [ -d "$service" ]; then
-              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest ./$service \
-                --build-arg PROJECT_DB_HOST=${{ secrets.PROJECT_DB_HOST }} \
-                --build-arg PROJECT_DB_USER=${{ secrets.PROJECT_DB_USER }} \
-                --build-arg PROJECT_DB_PASSWORD=${{ secrets.PROJECT_DB_PASSWORD }} \
-                --build-arg PROJECT_DB_NAME=${{ secrets.PROJECT_DB_NAME }} \
-                --build-arg PROJECT_DB_PORT=${{ secrets.PROJECT_DB_PORT }} \
-                --build-arg AWS_REGION=${{ secrets.AWS_REGION }} \
-                --build-arg DYNAMODB_TABLE_NAME=${{ secrets.NOTIFICATION_DB_TABLE_NAME }} \
-                --build-arg USER_DB_HOST=${{ secrets.USER_DB_HOST }} \
-                --build-arg USER_DB_USER=${{ secrets.USER_DB_USER }} \
-                --build-arg USER_DB_PASSWORD=${{ secrets.USER_DB_PASSWORD }} \
-                --build-arg USER_DB_NAME=${{ secrets.USER_DB_NAME }} \
-                --build-arg USER_DB_PORT=${{ secrets.USER_DB_PORT }} \
-                --build-arg DOCUMENT_DB_HOST=${{ secrets.DOCUMENT_DB_HOST }} \
-                --build-arg DOCUMENT_DB_USER=${{ secrets.DOCUMENT_DB_USER }} \
-                --build-arg DOCUMENT_DB_PASSWORD=${{ secrets.DOCUMENT_DB_PASSWORD }} \
-                --build-arg DOCUMENT_DB_NAME=${{ secrets.DOCUMENT_DB_NAME }} \
-                --build-arg DOCUMENT_DB_PORT=${{ secrets.DOCUMENT_DB_PORT }} \
-                --build-arg COMMENTARY_DB_HOST=${{ secrets.COMMENTARY_DB_HOST }} \
-                --build-arg COMMENTARY_DB_USER=${{ secrets.COMMENTARY_DB_USER }} \
-                --build-arg COMMENTARY_DB_PASSWORD=${{ secrets.COMMENTARY_DB_PASSWORD }} \
-                --build-arg COMMENTARY_DB_NAME=${{ secrets.COMMENTARY_DB_NAME }} \
-                --build-arg COMMENTARY_DB_PORT=${{ secrets.COMMENTARY_DB_PORT }}
-                
-              docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest
-            else
-              echo "Failed to find the path of directory of service $service"
-              exit 1
-            fi
-          done
-      
+        services=(
+          "createcommentary" "createproject" "deletecommentary" "deleteproject" 
+          "notificationhistory" "readcommentaries" "readproject" "receivenotification" 
+          "sendnotification" "updatecommentary" "updateproject" "audit-service" "create-user"
+          "createdocument" "delete-user" "deletedocument" "login" "read-user" "readdocument"
+          "update-user" "updatedocument"
+        )
+        
+        for service in "${services[@]}"
+        do
+          if [ -d "$service" ]; then
+            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest ./$service
+            docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest
+          else
+            echo "Failed to find the path of directory of service $service"
+            exit 1
+          fi
+        done
 
     - name: Paths of docker-compose
       run: |
